### ISSUE TITLE
Scorched 0.12.0 no longer compatible with httlib2 caching

### ISSUE THREAD

**Issue by ldaverio** [lugensa/scorched#53]
Hello,
I've just come across a problem which arose after upgrading scorched from 0.11.0 to 0.12.0, in relation with the use of caching in the httplib2 module. The following code:

from scorched import SolrInterface
from httplib2 import Http
si = SolrInterface(url='http://localhost:8983/solr/XXX', http_connection=Http('/tmp'))

works with scorched <= 0.11.0, but produces the following error with 0.12.0:

>   File "/Users/daverio/pydev/lib/python3.5/site-packages/scorched/connection.py", line 292, in \_\_init__
    self.schema = self.init_schema()
  File "/Users/daverio/pydev/lib/python3.5/site-packages/scorched/connection.py", line 298, in init_schema
    self.remote_schema_file))
  File "/Users/daverio/pydev/lib/python3.5/site-packages/scorched/connection.py", line 73, in request
    return self.http_connection.request(*args, **kwargs)
  File "/Users/daverio/pydev/lib/python3.5/site-packages/httplib2/\_\_init__.py", line 1176, in request
    (scheme, authority, request_uri, defrag_uri) = urlnorm(uri)
  File "/Users/daverio/pydev/lib/python3.5/site-packages/httplib2/\_\_init__.py", line 148, in urlnorm
    raise RelativeURIError("Only absolute URIs are allowed. uri = %s" % uri)
httplib2.RelativeURIError: Only absolute URIs are allowed. uri = GET

I haven't taken the time to investigate the problem yet. I'm not sure if I should continue using httplib2 caching.

**Comment by delijati** [comment]
Hi @ldaverio, the version <= 0.12.0. never really used [`http_connection`](https://github.com/lugensa/scorched/pull/51/files) . You could try https://github.com/ionrock/cachecontrol as we use `requests` for connection handling.

**Comment by delijati** [comment]
Seems tom bei solved !?
